---
token:
  # jwt token valid duration (in hours)
  duration: 168 # 7 days
server:
  port: 9000
auth:
  min_length_new_account_username: 4
  max_length_new_account_username: 20
  min_length_new_account_password: 4
  max_length_new_account_password: 30